title: P20 WIN Data Governance Manual
description: A resource for participating agencies and prospective data requestors
baseurl: "/data-governance" # the subpath of your site, e.g. /blog
url: "https://p20-win.github.io/data-governance/" # the base hostname & protocol for your site, e.g. http://example.com

# URLs
permalink: pretty

# Languages
languages: ["en"]
default_lang: "en"

# Build settings
remote_theme: pmarsceill/just-the-docs
favicon_ico: "/assets/favicon.ico"
search_enabled: true

nav_external_links: []

footer_external_links:
  en:
    - label: Data & Policy Analytics
      url: https://portal.ct.gov/datapolicy

footer_hosted_with_love:
  en:
    label: "GitHub Repository"
    url: https://github.com/P20-WIN/data-governance

# Collections
defaults:
  - scope:
      path: "**/*.md"
      type: "data_governance_structure"
    values:
      layout: "default"
      has_children: true
  - scope:
      path: "**/*.md"
      type: "key_processes"
    values:
      layout: "default"
      has_children: true
  - scope:
      path: "**/*.md"
      type: "policies"
    values:
      layout: "default"
      has_children: true

just_the_docs:
  collections:
    data_governance_structure:
      name: Data Governance Structure
      has_children: true
      nav_exclude: false
      search_exclude: false
      nav_fold: false
    key_processes:
      name: Key Processes
      has_children: true
      nav_exclude: false
      search_exclude: false
      nav_fold: true
    policies:
      name: Policies
      has_children: true
      nav_exclude: false
      search_exclude: false
      nav_fold: true
